// Generated by gencpp from file mine_picture/picture.msg
// DO NOT EDIT!


#ifndef MINE_PICTURE_MESSAGE_PICTURE_H
#define MINE_PICTURE_MESSAGE_PICTURE_H

#include <ros/service_traits.h>


#include <mine_picture/pictureRequest.h>
#include <mine_picture/pictureResponse.h>


namespace mine_picture
{

struct picture
{

typedef pictureRequest Request;
typedef pictureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct picture
} // namespace mine_picture


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mine_picture::picture > {
  static const char* value()
  {
    return "8dcd12f77a8502335873197b5e1c90ec";
  }

  static const char* value(const ::mine_picture::picture&) { return value(); }
};

template<>
struct DataType< ::mine_picture::picture > {
  static const char* value()
  {
    return "mine_picture/picture";
  }

  static const char* value(const ::mine_picture::picture&) { return value(); }
};


// service_traits::MD5Sum< ::mine_picture::pictureRequest> should match
// service_traits::MD5Sum< ::mine_picture::picture >
template<>
struct MD5Sum< ::mine_picture::pictureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mine_picture::picture >::value();
  }
  static const char* value(const ::mine_picture::pictureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mine_picture::pictureRequest> should match
// service_traits::DataType< ::mine_picture::picture >
template<>
struct DataType< ::mine_picture::pictureRequest>
{
  static const char* value()
  {
    return DataType< ::mine_picture::picture >::value();
  }
  static const char* value(const ::mine_picture::pictureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mine_picture::pictureResponse> should match
// service_traits::MD5Sum< ::mine_picture::picture >
template<>
struct MD5Sum< ::mine_picture::pictureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mine_picture::picture >::value();
  }
  static const char* value(const ::mine_picture::pictureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mine_picture::pictureResponse> should match
// service_traits::DataType< ::mine_picture::picture >
template<>
struct DataType< ::mine_picture::pictureResponse>
{
  static const char* value()
  {
    return DataType< ::mine_picture::picture >::value();
  }
  static const char* value(const ::mine_picture::pictureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINE_PICTURE_MESSAGE_PICTURE_H
