// Generated by gencpp from file mine_picture/pictureResponse.msg
// DO NOT EDIT!


#ifndef MINE_PICTURE_MESSAGE_PICTURERESPONSE_H
#define MINE_PICTURE_MESSAGE_PICTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mine_picture
{
template <class ContainerAllocator>
struct pictureResponse_
{
  typedef pictureResponse_<ContainerAllocator> Type;

  pictureResponse_()
    : feedback()  {
    }
  pictureResponse_(const ContainerAllocator& _alloc)
    : feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::mine_picture::pictureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mine_picture::pictureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pictureResponse_

typedef ::mine_picture::pictureResponse_<std::allocator<void> > pictureResponse;

typedef boost::shared_ptr< ::mine_picture::pictureResponse > pictureResponsePtr;
typedef boost::shared_ptr< ::mine_picture::pictureResponse const> pictureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mine_picture::pictureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mine_picture::pictureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mine_picture::pictureResponse_<ContainerAllocator1> & lhs, const ::mine_picture::pictureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mine_picture::pictureResponse_<ContainerAllocator1> & lhs, const ::mine_picture::pictureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mine_picture

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mine_picture::pictureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mine_picture::pictureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mine_picture::pictureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mine_picture::pictureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mine_picture::pictureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mine_picture::pictureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mine_picture::pictureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c14cdf907e5c7c7fd47292add15660f0";
  }

  static const char* value(const ::mine_picture::pictureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc14cdf907e5c7c7fULL;
  static const uint64_t static_value2 = 0xd47292add15660f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mine_picture::pictureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mine_picture/pictureResponse";
  }

  static const char* value(const ::mine_picture::pictureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mine_picture::pictureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string feedback\n"
;
  }

  static const char* value(const ::mine_picture::pictureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mine_picture::pictureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pictureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mine_picture::pictureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mine_picture::pictureResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINE_PICTURE_MESSAGE_PICTURERESPONSE_H
